contentitemexportablefields:
  contentitemfields:
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 7b6ca56e-ff03-4e14-8ed5-48ec42605d9c
inputs: []
name: Phil
outputs: []
starttaskid: "0"
tasks:
  "0":
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8b549f96-be09-4514-8f5b-a14f0cbae507
      iscommand: false
      name: ""
      version: -1
    taskid: 8b549f96-be09-4514-8f5b-a14f0cbae507
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4a59ebbf-ff8e-4abe-8724-bafe855f16d1
      iscommand: false
      name: This works!
      type: title
      version: -1
    taskid: 4a59ebbf-ff8e-4abe-8724-bafe855f16d1
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 245,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
